events {}

http {
  access_log off;
  error_log /dev/stderr warn;

  server {
    listen 9443 ssl;
    server_name api.openarc.test;

    ssl_certificate /tmp/api.crt;
    ssl_certificate_key /tmp/api.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache off;

    location / {
      proxy_pass http://openarc-api-m03:3000;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host api.openarc.test;
    }
  }
}
